import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToDoProvider from './Context/ToDoProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Todo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <ToDoProvider>
        {children}
      </ToDoProvider>
        </body>
     
    </html>
  )
}
